theme: jekyll-theme-minimal
title: Abigail Cormier's Homepage 
logo: ./Abigail_Cormier_Headshot.jpg
email: arc49966@uga.edu
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

nav:
  - title: Home
    url: ./
  - title: Research
    url: ./research.html
  - title: Teaching
    url: ./teaching.html

